name: Go
run-name: build and test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Build
        run: make go-build

      - name: Test
        run: make go-test
